---
# Welcome to WorldLimit
# version: 1.0.0
# Discord contact: ! Refaltor#7393
# Email contact: contact@nuketown.fr

version: 1.0.0

x: 1000
z: 1000

message: "You cannot go beyond 1000x | 1000z !"

worlds:
  - world
...